packages:
  - packages/*

catalog:
  '@types/node': 25.0.2
  '@vitest/ui': ^4.0.15
  eslint: ^9.17.0
  prettier: ^3.7.4
  solid-js: ^1.9.10
  typescript: ^5.7.2
  vite: ^7.3.0
  vitest: ^4.0.15
  zod: ^4.2.0

onlyBuiltDependencies:
  - esbuild
